= Collection of Java EE (EE4J) utilities

This project should collect small reusable libraries targetted to Java EE environments.
Some of the components target http://payara.fish[Payara] specifically, some only depend on standard Java EE APIs.

Currently following libraries are available:

link:payara-logback/[payara-logback]::
  Libraries, that enable to use https://logback.qos.ch/[logback] as only logging backend in Payara.
  
link:websecurity/[websecurity]::
  Servlet and JAX-RS filters for various security aspects, like standard headers, CORS or rate limiting.
  
link:ese/[ESE]::
   Library for implementing Event Sourced Entities in Java SE (and more).
   
== Roadmap

There are some more things I (@pdudits) plan to publish, but it takes some time to make them clean from project details:

* Cors headers filter with configurable behaviour
* Passive aggresive rate limiter, that puts requests on async wait list
* IP filter
* Request threadpool executor, that is better suitable for handling request peaks than standard ThreadPoolExecutor
